/**
 * Domain 3 — User Administration Constants
 */

export const USER_PERMISSIONS = {
  VIEW: 'USER.VIEW',
  CREATE: 'USER.CREATE',
  UPDATE: 'USER.UPDATE',
  DEACTIVATE: 'USER.DEACTIVATE',
  DELETE: 'USER.DELETE',
  INVITE: 'USER.INVITE',
  PASSWORD_RESET: 'USER.PASSWORD.RESET',
  UNLOCK: 'USER.UNLOCK',
  ROLE_ASSIGN: 'USER.ROLE.ASSIGN',
  SCOPE_ASSIGN: 'USER.SCOPE.ASSIGN',
  OVERRIDE_MANAGE: 'USER.OVERRIDE.MANAGE',
  DELEGATION_MANAGE: 'USER.DELEGATION.MANAGE',
  IMPORT: 'USER.IMPORT',
  EXPORT: 'USER.EXPORT',
  VENDOR_MANAGE: 'VENDORUSER.MANAGE',
} as const;

export const USER_TYPES = {
  INTERNAL: 'INTERNAL',
  VENDOR: 'VENDOR',
  SYSTEM: 'SYSTEM',
  SERVICE_ACCOUNT: 'SERVICE_ACCOUNT',
} as const;

export type UserType = (typeof USER_TYPES)[keyof typeof USER_TYPES];

export const SCOPE_CODES = {
  GLOBAL: 'GLOBAL',
  ORGANIZATION: 'ORGANIZATION',
  BUSINESS_UNIT: 'BUSINESS_UNIT',
  DEPARTMENT: 'DEPARTMENT',
  SECTION: 'SECTION',
  SELF: 'SELF',
} as const;

export type ScopeCode = (typeof SCOPE_CODES)[keyof typeof SCOPE_CODES];

export const INVITATION_PURPOSES = {
  INVITE: 'INVITE',
  PASSWORD_RESET: 'PASSWORD_RESET',
} as const;

export type InvitationPurpose =
  (typeof INVITATION_PURPOSES)[keyof typeof INVITATION_PURPOSES];

/**
 * Domain 3 Standard Error Codes (§5, §6, §7, §9)
 */
export const USER_ERROR_CODES = {
  // Section 5: User Lifecycle Errors
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  USER_USERNAME_EXISTS: 'USER_USERNAME_EXISTS',
  USER_TYPE_INVALID: 'USER_TYPE_INVALID',
  USER_EMPLOYEE_ID_REQUIRED: 'USER_EMPLOYEE_ID_REQUIRED',
  USER_VENDOR_INVALID: 'USER_VENDOR_INVALID',
  USER_ORG_UNIT_INVALID: 'USER_ORG_UNIT_INVALID',
  USER_SCOPE_DENIED: 'USER_SCOPE_DENIED',
  USER_SELF_ACTION: 'USER_SELF_ACTION',
  USER_LAST_ADMIN: 'USER_LAST_ADMIN',
  USER_IS_ORG_HEAD: 'USER_IS_ORG_HEAD',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_LOCKED: 'USER_LOCKED',

  // Section 6: Scope & Role Assignment Errors
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ASSIGNMENT_INVALID: 'ROLE_ASSIGNMENT_INVALID',
  SCOPE_ASSIGNMENT_INVALID: 'SCOPE_ASSIGNMENT_INVALID',
  SCOPE_ORG_UNIT_INVALID: 'SCOPE_ORG_UNIT_INVALID',
  SCOPE_ESCALATION: 'SCOPE_ESCALATION',
  SCOPE_VENDOR_NOT_ALLOWED: 'SCOPE_VENDOR_NOT_ALLOWED',
  SCOPE_DUPLICATE: 'SCOPE_DUPLICATE',
  SCOPE_NOT_FOUND: 'SCOPE_NOT_FOUND',

  // Section 7: Vendor User Errors
  VENDOR_REQUIRED: 'VENDOR_REQUIRED',
  VENDOR_ROLE_INVALID: 'VENDOR_ROLE_INVALID',
  VENDOR_SCOPE_NOT_ALLOWED: 'VENDOR_SCOPE_NOT_ALLOWED',
  VENDOR_ORG_UNIT_NOT_ALLOWED: 'VENDOR_ORG_UNIT_NOT_ALLOWED',

  // Section 9: Delegation Errors
  DELEGATION_SELF_NOT_ALLOWED: 'DELEGATION_SELF_NOT_ALLOWED',
  DELEGATION_INVALID_DATES: 'DELEGATION_INVALID_DATES',
  DELEGATION_OVERLAP: 'DELEGATION_OVERLAP',
  DELEGATION_INVALID_DELEGATE: 'DELEGATION_INVALID_DELEGATE',
  DELEGATION_CHAINED_NOT_ALLOWED: 'DELEGATION_CHAINED_NOT_ALLOWED',
  DELEGATION_NOT_FOUND: 'DELEGATION_NOT_FOUND',

  // Password & Invitation Errors
  INVITATION_INVALID_OR_EXPIRED: 'INVITATION_INVALID_OR_EXPIRED',
  PASSWORD_HISTORY_VIOLATION: 'PASSWORD_HISTORY_VIOLATION',
  PASSWORD_WEAK: 'PASSWORD_WEAK',
} as const;

export const INVITATION_EXPIRY_DAYS = 7;
export const PASSWORD_RESET_EXPIRY_HOURS = 1;
export const PASSWORD_HISTORY_CHECK_COUNT = 5;
export const PASSWORD_HISTORY_MAX_COUNT = 24;
export const MAX_FAILED_LOGIN_ATTEMPTS = 5;
export const ACCOUNT_LOCKOUT_MINUTES = 30;
