export const GRADE_BENEFIT_PERMISSIONS = {
  VIEW: 'SALARY_GRADE.CONFIGURATION.VIEW',
  CREATE: 'SALARY_GRADE.CONFIGURATION.CREATE',
  UPDATE: 'SALARY_GRADE.CONFIGURATION.UPDATE',
  DELETE: 'SALARY_GRADE.CONFIGURATION.DELETE',
} as const;

export const GRADE_BENEFIT_ERROR_CODES = {
  NOT_FOUND:
    'SALARY_GRADE_NOT_FOUND',

  DUPLICATE:
    'SALARY_GRADE_DUPLICATE',

  INVALID_DEPLOYMENT:
    'INVALID_DEPLOYMENT',

  INVALID_CATEGORY:
    'INVALID_CATEGORY',

  INVALID_DESIGNATION:
    'INVALID_DESIGNATION',

  INVALID_GRADE:
    'INVALID_GRADE',

  INVALID_TIER:
    'INVALID_TIER',

  INVALID_BENEFIT:
    'INVALID_BENEFIT',
} as const;

export const GRADE_BENEFIT_DEFAULTS = {
  IS_ACTIVE: true,
  IS_DELETED: false,
  PAGE: 1,
  PAGE_SIZE: 20,
} as const;