export const ASSIGNMENT_PERMISSIONS = {
  ROLE_ASSIGN: 'USER.ROLE.ASSIGN',
  SCOPE_ASSIGN: 'USER.SCOPE.ASSIGN',
  OVERRIDE_MANAGE: 'USER.OVERRIDE.MANAGE',
  VIEW: 'USER.VIEW',
} as const;

export const SCOPE_TYPE_CODES = {
  GLOBAL: 'GLOBAL',
  ORGANIZATION: 'ORGANIZATION',
  BUSINESS_UNIT: 'BUSINESS_UNIT',
  DEPARTMENT: 'DEPARTMENT',
  SECTION: 'SECTION',
  SELF: 'SELF',
} as const;

export type ScopeTypeCode =
  (typeof SCOPE_TYPE_CODES)[keyof typeof SCOPE_TYPE_CODES];
