/**
 * Defines all available permissions in the system.
 * These are used by the PermissionGuard to restrict access to endpoints.
 */
export const PERMISSIONS = {
  // Requisition Permissions
  REQUISITION_CREATE: 'REQUISITION.CREATE',
  REQUISITION_VIEW: 'REQUISITION.VIEW',
  REQUISITION_EDIT: 'REQUISITION.EDIT',
  REQUISITION_DELETE: 'REQUISITION.DELETE',

  REQUISITION_APPROVE: 'REQUISITION.APPROVE',
  REQUISITION_REJECT: 'REQUISITION.REJECT',

  // Budget Permissions
  BUDGET_VIEW: 'BUDGET.VIEW',
  BUDGET_LOCK: 'BUDGET.LOCK',
  BUDGET_RELEASE: 'BUDGET.RELEASE',

  // Interview Permissions
  INTERVIEW_SCHEDULE: 'INTERVIEW.SCHEDULE',
  INTERVIEW_BYPASS: 'INTERVIEW.BYPASS',

  // Candidate Permissions
  CANDIDATE_VIEW: 'CANDIDATE.VIEW',
  CANDIDATE_UNMASK: 'CANDIDATE.UNMASK',

  // Vendor Permissions
  VENDOR_VIEW: 'VENDOR.VIEW',

  // User & Role Management
  USER_MANAGE: 'USER.MANAGE',
  ROLE_MANAGE: 'ROLE.MANAGE',

  // Security & Auditing
  SECURITY_FAILED_LOGINS_VIEW: 'SECURITY.FAILED_LOGINS.VIEW',
  SECURITY_SESSIONS_REVOKE: 'SECURITY.SESSIONS.REVOKE',
  SECURITY_EVENTS_EXPORT: 'SECURITY.EVENTS.EXPORT',
  SECURITY_ADMIN: 'SECURITY.ADMIN',
  SECURITY_USERS_FORCE_LOGOUT: 'SECURITY.USERS.FORCE_LOGOUT',
  SECURITY_DASHBOARD_VIEW: 'SECURITY.DASHBOARD.VIEW',
  SECURITY_EVENTS_VIEW: 'SECURITY.EVENTS.VIEW',
  SECURITY_SESSIONS_VIEW: 'SECURITY.SESSIONS.VIEW',
} as const;

const copyable = [
  'REQUISITION.CREATE',
  'REQUISITION.VIEW',
  'REQUISITION.EDIT',
  'REQUISITION.DELETE',
  'REQUISITION.APPROVE',
  'REQUISITION.REJECT',
  'BUDGET.VIEW',
  'BUDGET.LOCK',
  'BUDGET.RELEASE',
  'INTERVIEW.SCHEDULE',
  'INTERVIEW.BYPASS',
  'CANDIDATE.VIEW',
  'CANDIDATE.UNMASK',
  'VENDOR.VIEW',
  'USER.MANAGE',
  'ROLE.MANAGE',
  'SECURITY.FAILED_LOGINS.VIEW',
  'SECURITY.SESSIONS.REVOKE',
  'SECURITY.EVENTS.EXPORT',
  'SECURITY.ADMIN',
  'SECURITY.USERS.FORCE_LOGOUT',
  'SECURITY.DASHBOARD.VIEW',
  'SECURITY.EVENTS.VIEW',
  'SECURITY.SESSIONS.VIEW',
];
